In [1]:
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display
from mpl_toolkits.mplot3d import Axes3D
from IPython.display import display

In [2]:
N  = 12
x  = np.linspace(0, 1, N)
y  = 0.75*x + 1
yn = y + np.random.normal(0, .3, size=(N))
D  = np.concatenate(([x], [y])).T

In [3]:
%matplotlib inline

@widgets.interact(m=(-1.5, 1.5, 0.05), b=(-3, 3, 0.1))
def update_plot(m=0, b=0):
    distance = m*x + b - yn
    #
    plt.figure(figsize=(8,8))
    plt.plot(x, m*x + b, color='red')
    plt.plot(x, yn, 'o')
    #
    for x_i, yn_i, d_i in zip(x, yn, distance):
        plt.plot([x_i, x_i], [yn_i, m*x_i + b], color='green', linestyle='dashed')
        plt.annotate(f"{d_i:.2f}", (x_i, yn_i), textcoords="offset points", xytext=(0,10), ha='center')
    #
    plt.ylim(-0.1, 2.5)
    plt.xlim(-0.1, 1.1)
    plt.annotate(f"Suma D = {distance.sum():5.3f}", (.8, 2.3), textcoords="offset points", xytext=(0,10), ha='center')
    plt.grid(True)
    plt.show()

interactive(children=(FloatSlider(value=0.0, description='m', max=1.5, min=-1.5, step=0.05), FloatSlider(value…

In [5]:
@widgets.interact(m=(-1.5, 1.5, 0.01), b=(-3, 3, 0.01))
def update_plot(m=0, b=0):
    distance = m*x + b - yn
    mse = (distance**2).sum()/distance.shape[0]
    #
    plt.figure(figsize=(8,8))
    plt.plot(x, m*x + b, color='red')
    plt.plot(x, yn, 'o')
    #
    for x_i, yn_i, d_i in zip(x, yn, distance):
        plt.plot([x_i, x_i], [yn_i, m*x_i + b], color='green', linestyle='dashed')
        plt.annotate(f"{d_i:.2f}", (x_i, yn_i), textcoords="offset points", xytext=(0,10), ha='center')
    #
    plt.ylim(-0.1, 2.5)
    plt.xlim(-0.1, 1.1)
    plt.annotate(f"Suma D = {distance.sum():5.3f}", (.8, 2.3), textcoords="offset points", xytext=(0,10), ha='center')
    plt.annotate(f"MSE = {mse:5.3f}", (.8, 2.2), textcoords="offset points", xytext=(0,10), ha='center')
    plt.grid(True)
    plt.show()

interactive(children=(FloatSlider(value=0.0, description='m', max=1.5, min=-1.5, step=0.01), FloatSlider(value…

In [6]:
X = np.insert(x[:, np.newaxis], 1, 1, axis=1)
w = (np.linalg.inv(X.T @ X) @ X.T) @ yn
w

array([0.62090542, 1.03903097])

In [11]:
N  = 30
xx = np.linspace(0, 1, N)
xx, yy = np.meshgrid(xx,xx)
xx, yy = xx.flatten(), yy.flatten()
zz = 2*xx + 3*yy - 1
sample = np.arange(xx.shape[0]).astype(np.int32)
np.random.shuffle(sample)
sample = sample[:N]

x, y, z = xx[sample], yy[sample], zz[sample]
zn      = z + np.random.normal(0, .1, size=(N))
xx, yy  = xx.reshape(N, N), yy.reshape(N, N)

%matplotlib widget

In [12]:
fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111, projection='3d')

@widgets.interact(w_1=(-2.5, 2.5, 0.01), 
                  w_2=(-3.2, 3.2, 0.01), 
                  b=(-2.0, 2.0, 0.01))
def update_plot(w_1=0.5, w_2=0.5, b=1):
    ax.clear()
    #d = -w_1 * x[0] - w_2 * y[0]  * z[0]
    #ax.scatter(x, y, z, color='blue')
    distance = 
    zz = w_1*xx + w_2*yy + b
    ax.plot_surface(xx, yy, zz, 
                    color='red',
                    alpha=0.5)
    ax.scatter(x, y, zn, color='blue')
    for x_i, y_i, z_i, zn_i in zip(x, y, z, zn):
        # Calcular la distancia vertical
        #distance = abs(a*x[i] + b*y[i] + c*z[i] + d) / np.sqrt(a**2 + b**2 + c**2)
        #ax.plot([x[i], x[i]], [y[i], y[i]], [z[i], -(a*x[i] + b*y[i] + d)*1. /c], color='gray', linestyle='dashed')
        ax.plot([x_i, x_i], [y_i, y_i], [zn_i, w_1*x_i + w_2*y_i + b], color='gray', linestyle='dashed')
        # Etiquetar la distancia vertical
        #ax.text(x[i], y[i], z[i], f"{distance:.2f}", color='black', fontsize=8)
    #
    fig.canvas.draw()
    plt.show()

interactive(children=(FloatSlider(value=0.5, description='w_1', max=2.5, min=-2.5, step=0.01), FloatSlider(val…

In [9]:
X = np.concatenate(([x], [y])).T
X = np.insert(X, X.shape[-1], 1, axis=1)
w = (np.linalg.inv(X.T @ X) @ X.T) @ zn
w


array([ 1.96195604,  3.02253347, -1.01273073])

In [6]:
# Generar puntos aleatorios en coordenadas (x, y, z)
%matplotlib widget

num_points = 50
x = np.random.rand(num_points)
y = np.random.rand(num_points)
z = np.random.rand(num_points)

# Crear una figura 3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Trazar los puntos
ax.scatter(x, y, z, color='blue')

# Función para actualizar el gráfico cuando se cambia el valor de a, b o c
@widgets.interact(a=(-1.0, 1.0, 0.01), b=(-1.0, 1.0, 0.01), c=(-1.0, 1.0, 0.01))
def update_plot(a=0.5, b=0.5, c=0.5):
    # Calcular la distancia del plano al origen
    d = -a * x[0] - b * y[0] - c * z[0]
    # Limpiar el gráfico anterior
    ax.clear()
    # Trazar el plano con los nuevos valores de a, b y c
    xx, yy = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
    zz = (-a * xx - b * yy - d) * 1. /c
    ax.plot_surface(xx, yy, zz, alpha=0.5)
    # Calcular y trazar las distancias verticales entre cada punto y el plano
    for i in range(num_points):
        # Calcular la distancia vertical
        distance = abs(a*x[i] + b*y[i] + c*z[i] + d) / np.sqrt(a**2 + b**2 + c**2)
        # Trazar una línea vertical para visualizar la distancia
        ax.plot([x[i], x[i]], [y[i], y[i]], [z[i], -(a*x[i] + b*y[i] + d)*1. /c], color='gray', linestyle='dashed')
        # Trazar el punto
        ax.scatter(x[i], y[i], z[i], color='blue')
        # Etiquetar la distancia vertical
        ax.text(x[i], y[i], z[i], f"{distance:.2f}", color='black', fontsize=8)
    # Configurar los ejes y mostrar el gráfico
    ax.set_xlim([0, 1])
    ax.set_ylim([0, 1])
    ax.set_zlim([0, 1])
    plt.show()

interactive(children=(FloatSlider(value=0.5, description='a', max=1.0, min=-1.0, step=0.01), FloatSlider(value…

In [7]:
np.random.uniform(size=(N))

array([0.08302335, 0.37961895, 0.4590777 , 0.34862934, 0.991721  ,
       0.47881383, 0.32168712, 0.44635104, 0.30957455, 0.57415183,
       0.38746819, 0.77583959, 0.80557077, 0.1192004 , 0.46392841,
       0.99051161, 0.03763788, 0.38090001, 0.04085915, 0.11082411])